# Matrizes

In [ ]:
import numpy as np

In [ ]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [ ]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [ ]:
matriz.shape

(2, 3)

Retorna a primeira linha

In [ ]:
matriz[0]

array([2, 3, 1])

Retorna a segunda linha

In [ ]:
matriz[1]

array([4, 5, 7])

Retorna a primeira linha e a terceira coluna

In [ ]:
matriz[0][2]

1

In [ ]:
matriz[1][2]

7

In [ ]:
matriz.shape

(2, 3)

i percorre as linhas; j percorre as colunas. N aposição 0 são as linhas e na possição 1 são as colunas

In [ ]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])  

[2 3 1]
2
3
1
[4 5 7]
4
5
7


# EXERCÍCIOS


1. Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

In [ ]:
matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])
matriz

array([[3, 4, 1],
       [3, 1, 5]])

In [ ]:
matriz.shape

(2, 3)

In [ ]:
soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    #print(matriz[i][j])
    soma += matriz[i][j]
print('Soma: ', soma)

Soma:  17


# FUNÇÕES


* Trechos de programa que recebem um determinado nome e podem ser chamados várias vezes durante a execução
* Principais vantagens: reutilização de código, modularidade e facilidade de manutenção do sistema

# Função sem parâmetro e sem retorno


In [ ]:
def mensagem():
  print('Texto da função')

In [ ]:
mensagem()
mensagem()
mensagem()

Texto da função
Texto da função
Texto da função


# Função com passagem de parâmetro

In [ ]:
def mensagem(texto):
  print(texto)

In [ ]:
mensagem('texto 1')
mensagem('texto 2')
mensagem('texto 3')

texto 1
texto 2
texto 3


In [ ]:
def soma(a, b):
  print(a + b)

In [ ]:
soma(2, 3)

5


In [ ]:
soma(3, 3)
soma(1, 2)

6
3


#Função com passagem de parâmetros e retorno


In [ ]:
def soma(a, b):
  return a + b

In [ ]:
soma(3, 2)

5

In [ ]:
# r = 7
r = soma(3, 2)
print(r)

5


In [ ]:
def calcula_energia_potencial_gravitacional(m, h, g = 10):
  '''
  Calcula a energia potencial gravitacional
  Argumentos:
  m: massa, entrada como uma variável float
  h: altura, entrada como uma variável float

  Argumento opcional:
  g: aceleração gravitacional, com valor default de 10
  '''
  e = g * m * h
  return e

In [ ]:
calcula_energia_potencial_gravitacional(30, 12)

3600

In [ ]:
calcula_energia_potencial_gravitacional(30, 12, 9.8)

3528.0

Help permite descrever a função

In [ ]:
help(calcula_energia_potencial_gravitacional)

Help on function calcula_energia_potencial_gravitacional in module __main__:

calcula_energia_potencial_gravitacional(m, h, g=10)
    Calcula a energia potencial gravitacional
    Argumentos:
    m: massa, entrada como uma variável float
    h: altura, entrada como uma variável float
    
    Argumento opcional:
    g: aceleração gravitacional, com valor default de 10



#Exercícios

1. Ler uma temperatura em graus Celsius e apresentá-la convertida em graus Fahrenheit. A fórmula de conversão é F = (9 * C + 160) / 5, na qual F é a temperatura em Fahrenheit e C é a temperatura em graus Celsius

Função para ler e retorna o valor da temperatura (não recebe parâmetro)
Função para fazer o cálculo (recebe como parâmetro a temperatura em graus Celsius)
Função para mostrar o resultado, recebendo como parâmetro o valor e fazendo a impressão

In [ ]:
def ler_temperatura():
  temperatura = float(input('Digite a temperatura em graus Celsius: '))
  return temperatura

In [ ]:
def converter(temperatura_celsius):
  temperatura_f = (9 * temperatura_celsius + 160) / 5
  return temperatura_f

In [ ]:
def mostrar(temperatura_f):
  print(temperatura_f)

In [ ]:
temperatura_c = ler_temperatura()
temperatura_f = converter(temperatura_c)
mostrar(temperatura_f)

Digite a temperatura em graus Celsius: 45
113.0


2. Efetuar o cálculo da quantidade de litros de combustível gasto em uma viagem, utilizando um automóvel que faz 12 Km por litro. Para obter o cálculo, o usuário deve fornecer o tempo gasto na viagem e a velocidade média durante ela. Desta forma, será possível obter a distância percorrida com a fórmula DISTANCIA = TEMPO * VELOCIDADE. Tendo o valor da distância, basta calcular a quantidade de litros de combustível utilizada na viagem, com a fórmula: LITROS_USADOS = DISTANCIA / 12. O programa deve apresentar os valores da velocidade média, tempo gasto na viagem, a distância percorrida e a quantidade de litros utilizada na viagem

Função para ler os valores (não recebe parâmetro e retorna os dois valores)
Função para calcular a distância (recebe como parâmetro o tempo e a velocidade e retorna a distância)
Função para calcular a quantidade de litros (recebe como parâmetro a distância e retorna os litros)
Função para apresentar o resultado (recebe como parâmetro os valores e somente imprime o resultado)

In [ ]:
def leitura():
  tempo = float(input('Digite o tempo da viagem: '))
  velocidade = float(input('Digite a velocidade média: '))
  return tempo, velocidade

In [ ]:
def calcula_distancia(tempo, velocidade):
  return tempo * velocidade

In [ ]:
def calcula_litros(distancia):
  return distancia / 12

In [ ]:
def imprime(velocidade, tempo, distancia, litros):
  print('Velocidade:', velocidade)
  print('Tempo:', tempo)
  print('Distância:', distancia)
  print('Litros:', litros)

In [ ]:
t, v = leitura()
d = calcula_distancia(t, v)
l = calcula_litros(d)
imprime(v, t, d, l)

Digite o tempo da viagem: 1
Digite a velocidade média: 80
Velocidade: 80.0
Tempo: 1.0
Distância: 80.0
Litros: 6.666666666666667
